const categoriesList = {
	categories: [
		{
			categoryId: 1,
			name: 'Technology',
			image: 'https://i.ibb.co/x5PzJPn/technology.png',
			childrenCount: 3,
			familyId: 1,
			parentId: 0,
			links: [
				{ path: 'c/111', name: 'Mobile Phones' },
				{ path: 'c/12', name: 'Laptops' },
				{ path: 'c/112', name: 'Mobile Phone Cases' },
			],
			color: '#1D84B0',
			showSpecifications: false,
		},
		{
			categoryId: 2,
			name: 'House - Carden',
			image: 'https://i.ibb.co/ZfvSdV7/house-Garden.png',
			childrenCount: 3,
			parentId: 0,
			links: [
				{ path: '/c', name: 'Refigerators' },
				{ path: '/c', name: 'Kitchens & Ovens' },
				{ path: '/c', name: 'Mobile Phone Cases' },
			],
			color: '#BCA580',
			showSpecifications: false,
		},
		{
			categoryId: 3,
			name: 'Fashion',
			image: 'https://i.ibb.co/1vnzQn1/fashion.png',
			childrenCount: 3,
			parentId: 0,
			links: [
				{ path: 'c/', name: 'Womens bags' },
				{ path: 'c/', name: 'Sunglasses' },
				{ path: 'c/', name: "Men's T-shirts" },
			],
			color: '#6F69AD',
			showSpecifications: false,
		},
		{
			categoryId: 4,
			name: 'Hobby - Sports',
			image: 'https://i.ibb.co/bKNgmhg/hobby-Sport.png',
			childrenCount: 3,
			parentId: 0,
			links: [
				{ path: 'c/', name: 'Sneakers' },
				{ path: 'c/', name: 'Sports shoes' },
				{ path: 'c/', name: 'Bicycles' },
			],
			color: '#20A8A6',
			showSpecifications: false,
		},
		{
			categoryId: 5,
			name: 'Health - Beauty',
			image: 'https://i.ibb.co/yNPWp6T/health-Beauty.png',
			childrenCount: 3,
			parentId: 0,
			links: [
				{ path: 'c/', name: 'Face creams' },
				{ path: 'c/', name: 'Protection Masks' },
				{ path: 'c/', name: 'Special Supplements' },
			],
			color: '#DC6C75',
			showSpecifications: false,
		},
		{
			categoryId: 6,
			name: 'Children - Babies',
			image: 'https://i.ibb.co/kmv9ggK/children-Babies.png',
			childrenCount: 3,
			parentId: 0,
			links: [
				{ path: 'c/', name: 'Sports Kids Shoes' },
				{ path: 'c/', name: "Children's Sneakers" },
				{ path: 'c/', name: "Children's Sandals" },
			],
			color: '#FEB555',
			showSpecifications: false,
		},
		{
			categoryId: 7,
			name: 'Auto - Moto',
			image: 'https://i.ibb.co/QbmNv7r/autoMoto.png',
			childrenCount: 3,
			parentId: 0,
			links: [
				{ path: 'c/', name: 'Tires' },
				{ path: 'c/', name: 'Machine Helmets' },
				{ path: 'c/', name: 'Car Audio Systems' },
			],
			color: '#6D7A87',
			showSpecifications: false,
		},
		{
			categoryId: 8,
			name: 'Business - B2B',
			image: 'https://i.ibb.co/McmXkmr/business-B2-B.png',
			childrenCount: 3,
			parentId: 0,
			links: [
				{ path: 'c/', name: 'Semi-permanent Nail Polish' },
				{ path: 'c/', name: 'Artificial nails' },
				{ path: 'c/', name: 'Nail Ovens' },
			],
			color: '#A2A2A2',
			showSpecifications: false,
		},
		//subcategories
		//Technology Family
		{
			categoryId: 11,
			name: 'Mobile',
			image: 'https://a.scdn.gr/ds/categories/86/20180525093944_f9e649e3.jpeg',
			childrenCount: 2,
			familyId: 1,
			parentId: 1,
			path: [1, 11],
			showSpecifications: false,
		},
		{
			categoryId: 12,
			name: 'Computers',
			image: 'https://c.scdn.gr/ds/categories/22/20171113120918_458cb257.jpeg',
			childrenCount: 0,
			familyId: 1,
			parentId: 1,
			path: [1, 12],
			showSpecifications: false,
		},
		{
			categoryId: 13,
			name: 'Sound',
			image: 'https://b.scdn.gr/ds/categories/767/20171113121140_e679f977.jpeg',
			childrenCount: 0,
			familyId: 1,
			parentId: 1,
			path: [1, 13],
			showSpecifications: false,
		},
		{
			categoryId: 14,
			name: 'Gaming',
			image:
				'https://d.scdn.gr/ds/categories/1864/20171113121624_bdd7dd99.jpeg',
			childrenCount: 0,
			familyId: 1,
			parentId: 1,
			path: [1, 14],
			showSpecifications: false,
		},
		{
			categoryId: 15,
			name: 'Image',
			image: 'https://b.scdn.gr/ds/categories/309/20171113120955_bd33680f.jpeg',
			childrenCount: 2,
			familyId: 1,
			parentId: 1,
			path: [1, 15],
			showSpecifications: false,
		},
		{
			categoryId: 16,
			name: 'Electronics',
			image: 'https://a.scdn.gr/ds/categories/144/20171113120938_495ee74c.jpeg',
			childrenCount: 0,
			familyId: 1,
			parentId: 1,
			path: [1, 16],
			showSpecifications: false,
		},
		{
			categoryId: 17,
			name: 'Wearables',
			image:
				'https://b.scdn.gr/ds/categories/1912/20171113121637_33abe91c.jpeg',
			childrenCount: 0,
			familyId: 1,
			parentId: 1,
			path: [1, 17],
			showSpecifications: false,
		},
		{
			categoryId: 18,
			name: 'Tablets & Accessories',
			image:
				'https://a.scdn.gr/ds/categories/1612/20171113121505_dbc4d0bb.jpeg',
			childrenCount: 0,
			familyId: 1,
			parentId: 1,
			path: [1, 18],
			showSpecifications: false,
		},
		{
			categoryId: 19,
			name: 'Photo & Video',
			image: 'https://b.scdn.gr/ds/categories/5/20171113120916_dfd75306.jpeg',
			childrenCount: 0,
			familyId: 1,
			parentId: 1,
			path: [1, 19],
			showSpecifications: false,
		},
		{
			categoryId: 20,
			name: 'Telephony',
			image: 'https://b.scdn.gr/ds/categories/2/20171113120916_9d335c35.jpeg',
			childrenCount: 0,
			familyId: 1,
			parentId: 1,
			path: [1, 20],
			showSpecifications: false,
		},

		{
			categoryId: 111,
			name: 'Mobile Phones',
			image: 'https://b.scdn.gr/ds/categories/40/20180525094054_5c0fb47b.jpeg',
			childrenCount: 0,
			familyId: 1,
			parentId: 11,
			path: [1, 11, 111],
			filters: [
				{
					title: 'Manufacturers',
					options: ['Samsung', 'Apple'],
				},
			],
			showSpecifications: true,
		},
		{
			categoryId: 112,
			name: 'Mobile Phone Cases',
			image: 'https://d.scdn.gr/ds/categories/579/20180525094216_aaa26b32.jpeg',
			childrenCount: 0,
			familyId: 1,
			parentId: 11,
			path: [1, 11, 112],
			showSpecifications: true,
		},
	],
};

module.exports = categoriesList;
